---
- name: "Common | fortios | hostname"
  fortinet.fortios.fortios_system_global:
    vdom: root
    system_global:
      hostname: "{{ common_hostname }}"

- name: "Common | fortios | NTP"
  fortinet.fortios.fortios_system_ntp:
    vdom: root
    system_ntp:
      ntpsync: enable
      type: custom
      ntpserver:
        "{{ common_ntp_servers | map('community.general.dict_kv', 'server') | list }}"

- name: "Common | fortios | DNS"
  fortinet.fortios.fortios_system_dns:
    vdom: root
    system_dns:
      primary: "{{ common_dns_servers[0] }}"
      secondary: "{{ common_dns_servers[1] | default(omit) }}"

- name: "Common | fortios | syslog destinations"
  fortinet.fortios.fortios_log_syslogd_setting:
    vdom: root
    log_syslogd_setting:
      status: enable
      server: "{{ item.host }}"
      port: "{{ item.port | default(514) }}"
  loop: "{{ common_syslog_servers }}"
  when: common_syslog_servers | length > 0
