---
galaxy_info:
  role_name: windows_ad
  namespace: examplecorp
  author: ExampleCorp Network Ops
  description: Base config and Active Directory Domain Services for Windows.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Windows
      versions: [all]
dependencies: []
