---
# Variables applied to every Windows host (AD, DNS, DHCP).

ansible_connection: winrm
ansible_user: ansible
ansible_winrm_transport: kerberos
ansible_winrm_server_cert_validation: validate

windows_ad_domain: "{{ org_domain }}"
windows_ad_safe_mode_password: "{{ vault_ad_safe_mode_password }}"
windows_ad_replica_of: hq-dc01.{{ org_domain }}
